# Generated by Django 3.1.7 on 2021-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_auto_20210329_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
